
RABBITMQ_DIR = rabbitmq
MICROSERVICES_DIR = microservices
CLIENT_DIR = client

# Define commands
DOCKER_COMPOSE = docker-compose up -d
PYTHON = python
UVICORN = uvicorn socket-service:app --host 0.0.0.0 --port 8001
NPM = npm start

.PHONY: all start-rabbitmq run-services start-client

# Default target
all: start-rabbitmq run-services start-client

# Start RabbitMQ using Docker Compose
start-rabbitmq:
	cd $(RABBITMQ_DIR) && $(DOCKER_COMPOSE)

# Run the data generator and the socket service
run-services:
	cd $(MICROSERVICES_DIR) && $(PYTHON) data-generator.py &
	cd $(MICROSERVICES_DIR) && $(UVICORN)

# Start the client application
start-client:
	cd $(CLIENT_DIR) && $(NPM)
